export const PAGES = {
  category: {
    name: 'Categories',
    id: 'category',
    listUrl: '/categories',
    addAction: 'New',
    addSuccess: 'Category Added Successfully',
    updateSuccess: 'Category updated Successfully',
    addUrl: '/category/add',
    headers: ['Code', 'Name', 'Status', 'Actions'],
  },
  assert: {
    name: 'Assets',
    id: 'asset',
    addAction: 'Add Asset',
    listUrl: '/list-assets',
    addUrl: '/asset/add',
    addSuccess: 'Asset Added Successfully',
    updateSuccess: 'Asset updated Successfully',
    headers: ['Code', 'Name', 'Status', 'Stock', 'Category', 'Type', 'Actions'],
  },
  stockItem: {
    name: 'Stock Items',
    id: 'stock-item',
    addAction: 'Add Stock Item',
    listUrl: '/list-stock',
    addUrl: '/stock/add',
    addSuccess: 'Stock Item Added Successfully',
    updateSuccess: 'Stock Item updated Successfully',
    headers: ['Code', 'Name', 'Status', 'Stock', 'Category', 'Type', 'Actions'],
  },
  transaction: {
    name: 'Transactions',
    id: 'transaction',
    listUrl: '/transactions',
    addAction: 'Add Transaction',
    addSuccess: 'Transaction Added Successfully',
    updateSuccess: 'Transaction updated Successfully',
    addUrl: '/transaction/add',
    headers: [
      'Asset',
      'Category',
      'Qty',
      'Status',
      'Date',
      'Location',
      'Requested By',
      'Created By',
      'Actions',
    ],
  },
  user: {
    name: 'Users',
    id: 'user',
    listUrl: '/users',
    addAction: 'Add User',
    addUrl: '/user/add',
    addSuccess: 'User Added Successfully',
    updateSuccess: 'User updated Successfully',
    headers: ['Name', 'Email', 'Phone', 'Role', 'Status', 'Actions'],
  },
  location: {
    name: 'Locations',
    id: 'location',
    listUrl: '/locations',
    addAction: 'Add Location',
    addUrl: '/location/add',
    addSuccess: 'Location Added Successfully',
    updateSuccess: 'Location updated Successfully',
    headers: ['Name', 'Type','Is site?', 'Status', 'Actions'],
  },
  supplier: {
    name: 'Suppliers',
    id: 'supplier',
    listUrl: '/suppliers',
    addAction: 'Add Supplier',
    addUrl: '/supplier/add',
    addSuccess: 'Supplier Added Successfully',
    updateSuccess: 'Supplier updated Successfully',
    headers: ['Name', 'Phone', 'Email', 'Actions'],
  },
  tanant: {
    name: 'Tanants',
    id: 'tanant',
    listUrl: '/tanants',
    addAction: 'Add Tanant',
    addUrl: '/tanant/add',
    addSuccess: 'Tanant Added Successfully',
    updateSuccess: 'Tanant updated Successfully',
    headers: ['Name', 'Room', 'Status', 'Actions'],
  },
  room: {
    name: 'Rooms',
    id: 'room',
    listUrl: '/rooms',
    addAction: 'Add Room',
    addUrl: '/room/add',
    addSuccess: 'Room Added Successfully',
    updateSuccess: 'Room updated Successfully',
    headers: ['Room No', 'Floor', 'Status', 'Actions'],
  },
  stockTake: {
    name: 'Stock Take',
    id: 'stockTake',
    listUrl: '/stock-take',
    addAction: 'Add Stock Take',
    addUrl: '/stock-take/add',
    addSuccess: 'Stock Take Added Successfully',
    updateSuccess: 'Stock Take updated Successfully',
    headers: ['Code', 'Name', 'Category', 'Count Stock'],
  },

  assetType: {
    name: 'Asset Types',
    id: 'assetType',
    listUrl: '/asset-types',
    addAction: 'Add Asset Type',
    addUrl: '/asset-types/add',
    addSuccess: 'Asset Type Added Successfully',
    updateSuccess: 'Asset Type updated Successfully',
    headers: ['Code', 'Name', 'Category', 'Actions'],
  },
  requisition: {
    name: 'Requisitions',
    id: 'requisition',
    listUrl: '/list-requisitions',
    addAction: 'Add Requisition',
    addUrl: '/requisition/add',
    addSuccess: 'Requisition Added Successfully',
    updateSuccess: 'Requisition updated Successfully',
    headers: ['Request Number', 'Site', 'Requested By', 'Status', 'Actions'],
  },
  roles: {
    name: 'Roles',
    id: 'roles',
    listUrl: '/roles',
    addAction: 'Add Role',
    addUrl: '/role/add',
    addSuccess: 'Role Added Successfully',
    updateSuccess: 'Role updated Successfully',
    headers: ['Name', 'Description', 'Actions'],
  },
};
